import webbrowser
url = 'https://www.google.com'

print('type space then enter')

webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
webbrowser.open_new_tab(url)
